#include<stdio.h>
#include<conio.h>
void sort(int a[],int n)
{
	int temp,j,k;
	for(j=0;j<n;j++)
	{
		for(k=j+1;k<n;k++)
		{
			if(a[j]>a[k])
			{
				temp=a[j];
				a[j]=a[k];
            a[k]=temp;
			}
		}
	}
}
void main()
{
	int source,destination,i,j,sum_supply=0,sum_demand=0,a[20],b,d,k,s,t,max,min;
	int cost[10][10],supply[10],demand[10],rf[10],cf[10],rp[10],cp[10],p,sum=0;
	printf("Enter no of source::");
	scanf("%d",&source);
	printf("Enter the Destination::");
	scanf("%d",&destination);
	printf("Enter the cost matrix::");
	for(i=0;i<source;i++)
	{
		for(j=0;j<destination;j++)
		{
			scanf("%d",&cost[i][j]);
		}
	}
	printf("Enter the Supply::");
	for(i=0;i<source;i++)
	{
		scanf("%d",&supply[i]);
		sum_supply=supply[i]+sum_supply;
	}
	printf("Enter the demand::");
	for(j=0;j<destination;j++)
	{
		scanf("%d",&demand[j]);
		sum_demand=demand[j]+sum_demand;
	}
	if(sum_supply!=sum_demand)
	{
		printf("Transporation problem not stable.....");
		if(sum_supply>sum_demand)
		{
			destination=destination+1;
			for(i=0;i<source;i++)
			{
				cost[i][destination-1]=0;
			}
			demand[destination-1]=sum_supply-sum_demand;
		}
		else
		{
			source=source+1;
			for(j=0;j<destination;j++)
			{
				cost[source-1][j]=0;
			}
			demand[source-1]=sum_demand-sum_supply;
		}
	}
	printf("\nThe transportation problem is:\n");
	for(i=0;i<destination;i++)
	{
		printf("D%d\t",i);
	}
	printf("supply");
	for(i=0;i<source;i++)
	{
		printf("\n O%d\t ",(i+1));
		for(j=0;j<destination;j++)
		{
			printf("%d\t",cost[i][j]);
		}
		printf("%d",supply[i]);
		printf("\n");
	}
	printf("Demand\t");
	for(i=0;i<destination;i++)
	{
		printf("%d\t",demand[i]);
	}
	for(i=0;i<source;i++)
	{
		rf[i]=0;
	}
	for(i=0;i<destination;i++)
	{
		cf[i]=0;
	}
	b=source,d=destination;
	while(b>0&&d>0)
	{
		for(i=0;i<source;i++)
		{
			rp[i]=-1;
		}
		for(i=0;i<destination;i++)
		{
			cp[i]=-1;
		}
		for(i=0;i<source;i++)
		{
			k=0;
			if(rf[i]!=1)
			{
				for(j=0;j<destination;j++)
				{
					if(cf[j]!=1)
					{
						a[k++]=cost[i][j];
					}
				}
				if(k==1)
				{
					rp[i]=a[0];
				}
				else
				{
					sort(a,k);
					rp[i]=a[1]-a[0];
				}
			}
		}
		for(i=0;i<destination;i++)
		{
			k=0;
			if(cf[i]!=1)
			{
				for(j=0;j<source;j++)
				{
					if(cf[j]!=1)
					{
						a[k++]=cost[j][i];
					}
				}
				if(k==1)
				{
					cp[i]=a[0];
				}
				else
				{
					sort(a,k);
					cp[i]=a[1]-a[0];
				}
			}
		}
		for(i=0;i<source;i++)
		{
			a[i]=rp[i];
		}
		for(j=0;j<destination;j++)
		{
			a[i+j]=cp[j];
		}
		max=a[0];
		p=0;
		for(i=1;i<source+destination;i++)
		{
			if(max<a[i])
			{
				max=a[i];
				p=i;
			}
		}
		min=1000;
		if(p>source-1)
		{
			p=p-source;
			if(cf[p]!=1)
			{
				for(i=0;i<source;i++)
				{
					if(rf[i]!=1)
					{
						if(min>cost[i][p])
						{
							min=cost[i][p];
							s=i;
							t=p;
						}
					}
				}
			}
		}
		else
		{
			if(rf[p]!=1)
			{
				for(i=0;i<destination;i++)
				{
					if(cf[i]!=1)
					{
						if(min>cost[p][i])
						{
							min=cost[p][i];
							s=p;
							t=i;
						}
					}
				}
			}
		}
		if(supply[s]<demand[t])
		{
			sum=sum+cost[s][t]*supply[s];
			demand[t]=demand[t]*supply[s];
			rf[s]=1;
			b--;
		}
		else if(supply[s]>demand[t])
		{
			sum=sum+(cost[s][t]*demand[t]);
			supply[s]=supply[s]-demand[t];
			cf[t]=1;
			d--;
		}
		else
		{
			sum=sum+cost[s][t]*demand[t];
			cf[t]=1;
			rf[s]=1;
			b--;
			d--;
		}
	}
   printf("\n\n minimum cost: %d",sum);
}